SET LIST ON;

/* --- Por setor: contagem E somas. Contar linha nao pega valor trocado. --- */
SELECT SETOR_ID,
       COUNT(*) AS LANCAMENTOS,
       SUM(VALOR_PAGO) AS SOMA_PAGA,
       SUM(VALOR_PREVISTO) AS SOMA_PREVISTA,
       MIN(DATA_VENCIMENTO) AS VENC_MIN,
       MAX(DATA_VENCIMENTO) AS VENC_MAX
  FROM REGISTRO_DE_GASTOS
 GROUP BY SETOR_ID
 ORDER BY SETOR_ID;

SELECT COUNT(*) AS TOTAL_LANCAMENTOS FROM REGISTRO_DE_GASTOS;

/* --- Cadastros por setor --- */
SELECT SETOR_ID, COUNT(*) AS CATEGORIAS      FROM CATEGORIA          GROUP BY SETOR_ID ORDER BY 1;
SELECT SETOR_ID, COUNT(*) AS SUBCATEGORIAS   FROM SUBCATEGORIA       GROUP BY SETOR_ID ORDER BY 1;
SELECT SETOR_ID, COUNT(*) AS CONTAS          FROM CONTAS             GROUP BY SETOR_ID ORDER BY 1;
SELECT SETOR_ID, COUNT(*) AS FORMAS          FROM FORMA_DE_PAGAMENTO GROUP BY SETOR_ID ORDER BY 1;

/* --- Nada pode ficar sem setor: seria invisivel para as duas operarias --- */
SELECT (SELECT COUNT(*) FROM REGISTRO_DE_GASTOS WHERE SETOR_ID IS NULL) AS G_SEM_SETOR,
       (SELECT COUNT(*) FROM CATEGORIA          WHERE SETOR_ID IS NULL) AS C_SEM_SETOR,
       (SELECT COUNT(*) FROM SUBCATEGORIA       WHERE SETOR_ID IS NULL) AS S_SEM_SETOR,
       (SELECT COUNT(*) FROM CONTAS             WHERE SETOR_ID IS NULL) AS N_SEM_SETOR,
       (SELECT COUNT(*) FROM FORMA_DE_PAGAMENTO WHERE SETOR_ID IS NULL) AS F_SEM_SETOR,
       (SELECT COUNT(*) FROM LOGIN              WHERE SETOR_ID IS NULL) AS L_SEM_SETOR
  FROM RDB$DATABASE;

/* --- FK orfa. O banco recusaria, mas conferir custa nada e prova. --- */
SELECT (SELECT COUNT(*) FROM REGISTRO_DE_GASTOS g WHERE NOT EXISTS
          (SELECT 1 FROM CATEGORIA x WHERE x.CATEGORIA_ID = g.CATEGORIA_ID)) AS ORFA_CATEGORIA,
       (SELECT COUNT(*) FROM REGISTRO_DE_GASTOS g WHERE NOT EXISTS
          (SELECT 1 FROM SUBCATEGORIA x WHERE x.SUBCATEGORIA_ID = g.SUBCATEGORIA_ID)) AS ORFA_SUBCAT,
       (SELECT COUNT(*) FROM REGISTRO_DE_GASTOS g WHERE NOT EXISTS
          (SELECT 1 FROM CONTAS x WHERE x.CONTA_ID = g.CONTA_ID)) AS ORFA_CONTA,
       (SELECT COUNT(*) FROM REGISTRO_DE_GASTOS g WHERE NOT EXISTS
          (SELECT 1 FROM FORMA_DE_PAGAMENTO x WHERE x.FORMA_DE_PAGAMENTO_ID = g.FORMA_DE_PAGAMENTO_ID)) AS ORFA_FORMA,
       (SELECT COUNT(*) FROM REGISTRO_DE_GASTOS g WHERE NOT EXISTS
          (SELECT 1 FROM LOGIN x WHERE x.LOGIN_ID = g.USERID)) AS ORFA_USUARIO
  FROM RDB$DATABASE;

/* --- Mistura entre setores: lancamento de um usando cadastro do outro --- */
SELECT (SELECT COUNT(*) FROM REGISTRO_DE_GASTOS g JOIN CATEGORIA c ON c.CATEGORIA_ID = g.CATEGORIA_ID
          WHERE g.SETOR_ID <> c.SETOR_ID) AS MISTURA_CATEGORIA,
       (SELECT COUNT(*) FROM REGISTRO_DE_GASTOS g JOIN SUBCATEGORIA s ON s.SUBCATEGORIA_ID = g.SUBCATEGORIA_ID
          WHERE g.SETOR_ID <> s.SETOR_ID) AS MISTURA_SUBCAT,
       (SELECT COUNT(*) FROM REGISTRO_DE_GASTOS g JOIN CONTAS n ON n.CONTA_ID = g.CONTA_ID
          WHERE g.SETOR_ID <> n.SETOR_ID) AS MISTURA_CONTA,
       (SELECT COUNT(*) FROM SUBCATEGORIA s JOIN CATEGORIA c ON c.CATEGORIA_ID = s.CATEGORIA_ID
          WHERE s.SETOR_ID <> c.SETOR_ID) AS SUBCAT_EM_CATEG_DE_OUTRO
  FROM RDB$DATABASE;

/* --- Generators acima do maximo --- */
SELECT GEN_ID(GEN_REGISTRO_DE_GASTOS_ID, 0) AS GEN_GASTOS,
       (SELECT MAX(GASTOS_ID) FROM REGISTRO_DE_GASTOS) AS MAX_GASTOS,
       GEN_ID(GEN_CATEGORIA_ID, 0) AS GEN_CATEG,
       (SELECT MAX(CATEGORIA_ID) FROM CATEGORIA) AS MAX_CATEG,
       GEN_ID(GEN_SUBCATEGORIA_ID, 0) AS GEN_SUB,
       (SELECT MAX(SUBCATEGORIA_ID) FROM SUBCATEGORIA) AS MAX_SUB
  FROM RDB$DATABASE;

SET LIST OFF;
SET WIDTH NOME 22;
SELECT l.LOGIN_ID, l.NOME, l.NIVEL, l.SETOR_ID,
       (SELECT COUNT(*) FROM REGISTRO_DE_GASTOS g WHERE g.USERID = l.LOGIN_ID) AS LANCOU
  FROM LOGIN l ORDER BY l.LOGIN_ID;
