<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\AgendaFinanceira.Dominio\AgendaFinanceira.Dominio.csproj" />
    <ProjectReference Include="..\AgendaFinanceira.Infraestrutura\AgendaFinanceira.Infraestrutura.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.*" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>37470bc1-d507-4b09-9e3f-37a3c73c20b0</UserSecretsId>
  </PropertyGroup>

</Project>
